#!/usr/bin/env bash
# Export session status to .claude/session-status.md
# Called manually or on token threshold (~90%)

set -e
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
STATUS_FILE="$ROOT/.claude/session-status.md"

# For now, just report that export was triggered
# In practice, this would be regenerated by reading task list, logs, etc.

echo "📊 Session status exported to $STATUS_FILE"
echo "Token threshold: check settings for 90% alert"
echo ""
echo "Quick status:"
echo "  - Completed: parser + multi-agent framework"
echo "  - Working on: session export infrastructure"
echo "  - Next: handle periodic monitoring"
