import Foundation

/// Structured header-level information extracted from a bank statement file.
/// All fields are optional because different banks expose different metadata.
/// Monetary fields use minor units (paise).
public struct StatementMetadata: Codable, Sendable, Equatable {
    /// Account holder's full name as printed on the statement.
    public let customerName: String?
    /// Bank-assigned customer or CIF identifier.
    public let customerId: String?
    /// Last 4 digits of the account or card number used for display.
    public let accountNumber: String?
    /// Full masked or unmasked account number as found in the statement.
    public let fullAccountNumber: String?
    /// Account product type, e.g. `"Savings"` or `"Current"`.
    public let accountType: String?
    /// Credit card variant, e.g. `"Platinum"` or `"Regalia"`.
    public let cardType: String?
    /// Branch name associated with the account.
    public let branch: String?
    /// Numeric branch or sort code.
    public let branchCode: String?
    /// Registered mailing address.
    public let address: String?
    /// Registered email address.
    public let email: String?
    /// Registered phone number.
    public let phone: String?
    /// IFSC code for the home branch.
    public let ifsc: String?
    /// MICR code for the home branch.
    public let micr: String?
    /// Opening balance at the start of the statement period, in paise.
    public let openingBalance: Int64?
    /// Closing balance at the end of the statement period, in paise.
    public let closingBalance: Int64?
    /// Number of debit transactions in the statement.
    public let debitCount: Int?
    /// Number of credit transactions in the statement.
    public let creditCount: Int?
    /// Timestamp when the statement was generated by the bank.
    public let generatedAt: Date?

    public init(
        customerName: String? = nil,
        customerId: String? = nil,
        accountNumber: String? = nil,
        fullAccountNumber: String? = nil,
        accountType: String? = nil,
        cardType: String? = nil,
        branch: String? = nil,
        branchCode: String? = nil,
        address: String? = nil,
        email: String? = nil,
        phone: String? = nil,
        ifsc: String? = nil,
        micr: String? = nil,
        openingBalance: Int64? = nil,
        closingBalance: Int64? = nil,
        debitCount: Int? = nil,
        creditCount: Int? = nil,
        generatedAt: Date? = nil
    ) {
        self.customerName = customerName
        self.customerId = customerId
        self.accountNumber = accountNumber
        self.fullAccountNumber = fullAccountNumber
        self.accountType = accountType
        self.cardType = cardType
        self.branch = branch
        self.branchCode = branchCode
        self.address = address
        self.email = email
        self.phone = phone
        self.ifsc = ifsc
        self.micr = micr
        self.openingBalance = openingBalance
        self.closingBalance = closingBalance
        self.debitCount = debitCount
        self.creditCount = creditCount
        self.generatedAt = generatedAt
    }
}
