//
//  Transaction.swift
//  FinanceCore
//
//  Created by Pratik Goel on 13/05/26.
//

import Foundation
import GRDB

/// Indicates whether money left (debit) or entered (credit) the ledger.
public enum TransactionType: String, Sendable, Codable {
    case debit
    case credit
}

/// Core financial event persisted in SQLite. Belongs to a ``Ledger`` and is immutable after import.
/// Amounts are always stored as minor units (e.g. paise for INR) to avoid floating-point rounding.
public struct Transaction:
    Identifiable,
    Codable,
    Sendable,
    FetchableRecord,
    PersistableRecord {
    public let id: UUID
    /// Foreign key to the parent ``Ledger``; nil only for orphaned/in-flight transactions.
    public let ledgerId: UUID?
    /// Denormalised account reference for queries that bypass the ledger join.
    public let accountID: UUID?
    /// Denormalised card reference; populated when the ledger kind is ``LedgerKind/creditCard``.
    public let cardID: UUID?
    public let postedAt: Date
    public let description: String
    /// Transaction amount in currency minor units (e.g. paise). Always positive; sign conveyed by `transactionType`.
    public let amountMinorUnits: Int64
    public let currencyCode: String
    public let transactionType: TransactionType
    /// Deterministic hash produced by the parser used to deduplicate reimported statements.
    public let sourceFingerprint: String?
    /// Predicted or user-confirmed category ID from the intelligence layer. Matches CategoryTaxonomy IDs.
    public let categoryId: String?
    /// Canonical merchant name resolved by MerchantNormalizer.
    public let merchantName: String?
    /// Account closing balance (in minor units) after this transaction, from bank statements with a running balance.
    public let closingBalanceMinorUnits: Int64?
    /// Intent ID assigned by the RuleEngine (e.g. "salary", "rent"). Added in v10 migration.
    public let intentId: String?
    /// ID of the resolved person entity for UPI/NEFT/IMPS person transfers. Added in v10 migration.
    public let resolvedPersonId: String?
    /// Pipeline version string that last enriched this transaction. Added in v10 migration.
    public let intelligenceVersion: String?

    // MARK: Enrichment provenance (v23)

    /// Timestamp of the last intelligence enrichment pass.
    public let lastEnrichedAt: Date?
    /// Source of the category prediction: "rule", "knn", "coreml", "fallback", "userCorrection".
    public let intelligenceSource: String?
    /// Model version string from the classifier that produced the category prediction.
    public let intelligenceModelVersion: String?
    /// Config version string active at the time of enrichment.
    public let intelligenceConfigVersion: String?
    /// True when the user has explicitly set the merchant name; prevents intelligence overwrite.
    public let isUserCorrectedMerchant: Bool

    // MARK: Enrichment (v26)

    /// Human-readable description generated by the intelligence pipeline. Nil until first enrichBatch run.
    public let enrichedDescription: String?
    /// UUID string of the reconciled counterpart transaction (e.g. bank debit linked to card credit payment).
    public let linkedTransactionId: String?

    public init(
        id: UUID = UUID(),
        ledgerId: UUID? = nil,
        accountID: UUID? = nil,
        cardID: UUID? = nil,
        postedAt: Date,
        description: String,
        amountMinorUnits: Int64,
        currencyCode: String,
        transactionType: TransactionType = .debit,
        sourceFingerprint: String? = nil,
        categoryId: String? = nil,
        merchantName: String? = nil,
        closingBalanceMinorUnits: Int64? = nil,
        intentId: String? = nil,
        resolvedPersonId: String? = nil,
        intelligenceVersion: String? = nil,
        lastEnrichedAt: Date? = nil,
        intelligenceSource: String? = nil,
        intelligenceModelVersion: String? = nil,
        intelligenceConfigVersion: String? = nil,
        isUserCorrectedMerchant: Bool = false,
        enrichedDescription: String? = nil,
        linkedTransactionId: String? = nil
    ) {
        self.id = id
        self.ledgerId = ledgerId
        self.accountID = accountID
        self.cardID = cardID
        self.postedAt = postedAt
        self.description = description
        self.amountMinorUnits = amountMinorUnits
        self.currencyCode = currencyCode
        self.transactionType = transactionType
        self.sourceFingerprint = sourceFingerprint
        self.categoryId = categoryId
        self.merchantName = merchantName
        self.closingBalanceMinorUnits = closingBalanceMinorUnits
        self.intentId = intentId
        self.resolvedPersonId = resolvedPersonId
        self.intelligenceVersion = intelligenceVersion
        self.lastEnrichedAt = lastEnrichedAt
        self.intelligenceSource = intelligenceSource
        self.intelligenceModelVersion = intelligenceModelVersion
        self.intelligenceConfigVersion = intelligenceConfigVersion
        self.isUserCorrectedMerchant = isUserCorrectedMerchant
        self.enrichedDescription = enrichedDescription
        self.linkedTransactionId = linkedTransactionId
    }
}

public extension Transaction {
    /// GRDB column references for type-safe query building; mirrors the `transactions` table schema.
    enum Columns {
        static let id = Column(CodingKeys.id)
        static let ledgerId = Column(CodingKeys.ledgerId)
        static let accountID = Column(CodingKeys.accountID)
        static let cardID = Column(CodingKeys.cardID)
        static let postedAt = Column(CodingKeys.postedAt)
        static let description = Column(CodingKeys.description)
        static let amountMinorUnits = Column(CodingKeys.amountMinorUnits)
        static let currencyCode = Column(CodingKeys.currencyCode)
        static let transactionType = Column(CodingKeys.transactionType)
        static let sourceFingerprint = Column(CodingKeys.sourceFingerprint)
        static let categoryId = Column(CodingKeys.categoryId)
        static let merchantName = Column(CodingKeys.merchantName)
        static let closingBalanceMinorUnits = Column(CodingKeys.closingBalanceMinorUnits)
        static let intentId = Column(CodingKeys.intentId)
        static let resolvedPersonId = Column(CodingKeys.resolvedPersonId)
        static let intelligenceVersion = Column(CodingKeys.intelligenceVersion)
        static let lastEnrichedAt = Column(CodingKeys.lastEnrichedAt)
        static let intelligenceSource = Column(CodingKeys.intelligenceSource)
        static let intelligenceModelVersion = Column(CodingKeys.intelligenceModelVersion)
        static let intelligenceConfigVersion = Column(CodingKeys.intelligenceConfigVersion)
        static let isUserCorrectedMerchant = Column(CodingKeys.isUserCorrectedMerchant)
        static let enrichedDescription = Column(CodingKeys.enrichedDescription)
        static let linkedTransactionId = Column(CodingKeys.linkedTransactionId)
    }
}

public extension Transaction {
    static let databaseTableName = "transactions"

    /// Creates the `transactions` table with all required columns, indexes, and the
    /// `(ledgerId, sourceFingerprint)` unique constraint that powers deduplication.
    static func createTable(
        in database: Database
    ) throws {
        try database.create(
            table: databaseTableName
        ) { table in
            table.column("id", .text)
                .primaryKey()

            table.column("ledgerId", .text)
                .indexed()
                .references(
                    Ledger.databaseTableName,
                    column: "id",
                    onDelete: .cascade
                )

            table.column("accountID", .text)
                .indexed()

            table.column("cardID", .text)
                .indexed()

            table.column("postedAt", .datetime)
                .notNull()
                .indexed()

            table.column("description", .text)
                .notNull()

            table.column("amountMinorUnits", .integer)
                .notNull()

            table.column("currencyCode", .text)
                .notNull()

            table.column("transactionType", .text)
                .notNull()
                .defaults(to: "debit")

            table.column("sourceFingerprint", .text)

            table.column("closingBalanceMinorUnits", .integer)

            table.uniqueKey(["ledgerId", "sourceFingerprint"])
        }
    }
}
